USE SPJ
SELECT  DISTINCT JNO 没有使用天津供应商生产的红零件的工程号
FROM SPJ
WHERE JNO NOT IN (SELECT JNO
				  FROM SPJ,P,S 
				  WHERE S.CITY='天津' AND COLOR='红' AND S.SNO=SPJ.SNO  AND P.PNO=SPJ.PNO)



USE SPJ
SELECT JNO 没有使用天津供应商生产的红零件的工程号
FROM J
WHERE EXISTS
	  (SELECT *
	   FROM SPJ
	   WHERE SPJ.JNO = J.JNO
	  )
	  AND NOT EXISTS
	  (SELECT *
	   FROM (SELECT PNO,SNO
			 FROM (SELECT PNO
				   FROM P
				   WHERE COLOR = '红')AS RED,				/*先选择，后连接*/
				   (SELECT SNO
					FROM S
					WHERE CITY = '天津')AS TIANJIN
			) AS REDTJ
	   WHERE EXISTS
			 (SELECT *
			  FROM SPJ
			  WHERE JNO = J.JNO
				AND PNO = REDTJ.PNO
				AND SNO = REDTJ.SNO
			 )
	  )


USE SPJ
SELECT DISTINCT JNO 没有使用天津供应商生产的红零件的工程号
FROM SPJ spj1
WHERE  NOT EXISTS
	  (SELECT *
	   FROM (SELECT PNO,SNO
			 FROM (SELECT PNO
				   FROM P
				   WHERE COLOR = '红')AS RED,				/*先选择，后连接*/
				   (SELECT SNO
					FROM S
					WHERE CITY = '天津')AS TIANJIN
			) AS REDTJ
	   WHERE EXISTS
			 (SELECT *
			  FROM SPJ spj2
			  WHERE spj2.JNO = spj1.JNO
				AND PNO = REDTJ.PNO
				AND SNO = REDTJ.SNO
			 )
	  )