use SPJ

/*1*/
GO
BEGIN TRAN

SELECT * FROM S		/*删除前的表格*/
SELECT * FROM SPJ

DELETE FROM SPJ WHERE SNO = 'S2'
DELETE FROM S WHERE SNO = 'S2'

SELECT * FROM S		/*删除后的表格*/
SELECT * FROM SPJ

ROLLBACK

/*2*/
GO
BEGIN TRAN

SELECT * FROM S		/*删除前的表格*/
SELECT * FROM SPJ

DECLARE @fun VARCHAR(200)
SET @fun = 'ALTER TABLE SPJ DROP CONSTRAINT FK_SPJ_S_SNO'										/*删除外键约束*/
EXEC(@fun)

DELETE FROM S WHERE SNO = 'S2'
DELETE FROM SPJ WHERE SNO = 'S2'

SELECT * FROM S		/*删除后的表格*/
SELECT * FROM SPJ

SET @fun = 'ALTER TABLE SPJ ADD CONSTRAINT FK_SPJ_S_SNO FOREIGN KEY (SNO) REFERENCES S(SNO)'	/*重新添加外键约束*/
EXEC(@fun)

ROLLBACK