/*不考虑零件由不同供应商提供
  J2是巧合*/
use SPJ
SELECT PNAME, QTY
FROM (SELECT PNO, PNAME
	  FROM P) AS PNOPNAME,(SELECT PNO, QTY
						   FROM SPJ
						   WHERE JNO = 'J2') AS PNOQTY
WHERE PNOPNAME.PNO = PNOQTY.PNO
ORDER BY PNAME


/*考虑零件是由不同供应商提供的*/
SELECT PNAME 零件名称, SUM(QTY) 零件数量
FROM (SELECT TOP 100 PERCENT PNAME, QTY									/*必须加上 SELECT TOP 100 PERCENT, 不然order by 不能在子查询中*/
	  FROM (SELECT PNO, PNAME											/*因为对于一个表的SELECT,返回的并不是一个表格，而是一个游标*/
			FROM P) AS PNOPNAME,(SELECT PNO, QTY
								 FROM SPJ
								 WHERE JNO = 'J2') AS PNOQTY
	  WHERE PNOPNAME.PNO = PNOQTY.PNO
	  ORDER BY PNAME) AS RESULT
GROUP BY RESULT.PNAME