use SPJ
SELECT JNAME
FROM (SELECT JNO, JNAME
	  FROM J) AS JNOJNAME, (SELECT DISTINCT JNO
							FROM SPJ
							WHERE SNO IN (SELECT SNO
										  FROM S
										  WHERE CITY = '…œ∫£')) AS JNOTEMP
WHERE JNOJNAME.JNO = JNOTEMP.JNO