SELECT SPJ.SNO, SNAME, MAX(QTY), MIN(QTY)
FROM SPJ, S
WHERE SPJ.SNO = S.SNO
ORDER BY S.SNO

SELECT SPJ.SNO, SNAME, QTY
FROM SPJ, S
WHERE SPJ.SNO = S.SNO
ORDER BY S.SNO

SELECT SNO, SNAME, MAX(QTY) 最大数量, MIN(QTY) 最小数量
FROM (SELECT TOP (100) PERCENT SPJ.SNO, QTY, SNAME
	  FROM SPJ, S
	  WHERE SPJ.SNO = S.SNO
	  ORDER BY S.SNO) AS TEMP
GROUP BY SNO, SNAME

SELECT SNO, MAX(QTY) 最大数量, MIN(QTY) 最小数量
FROM (SELECT TOP (100) PERCENT SPJ.SNO, QTY, SNAME
	  FROM SPJ, S
	  WHERE SPJ.SNO = S.SNO
	  ORDER BY S.SNO) AS TEMP
GROUP BY SNO